import {
  M_NoticeBoardsListContainer,
  M_NoticeBoardsListTab,
  M_NoticeBoardsListTabList,
  M_NoticeBoardsListTabPanel,
  M_NoticeBoardsListTabPanels,
  M_NoticeBoardsListTabs,
} from '../../style/noticeBoards/noticeBoardsList.style';
import { NoticeBoardItem } from './NoticeBoardsItem';
import { NoticeBoardLists } from './NoticeBoardsLists';

export const NoticeBoardsList = () => {
  return (
    <>
      <M_NoticeBoardsListContainer>
        <M_NoticeBoardsListTabs
          variant='soft-rounded'
          colorScheme='blue'
        >
          <M_NoticeBoardsListTabList>
            <M_NoticeBoardsListTab>
              최근
            </M_NoticeBoardsListTab>
            <M_NoticeBoardsListTab>
              인기
            </M_NoticeBoardsListTab>
          </M_NoticeBoardsListTabList>
          <M_NoticeBoardsListTabPanels>
            <M_NoticeBoardsListTabPanel>
              <NoticeBoardLists>
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
              </NoticeBoardLists>
            </M_NoticeBoardsListTabPanel>
            <M_NoticeBoardsListTabPanel>
              <NoticeBoardLists>
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
                <NoticeBoardItem
                  id='1'
                  title='제목'
                  writer='신권호'
                  date='5분전'
                />
              </NoticeBoardLists>
            </M_NoticeBoardsListTabPanel>
          </M_NoticeBoardsListTabPanels>
        </M_NoticeBoardsListTabs>
      </M_NoticeBoardsListContainer>
    </>
  );
};
